### ISSUE TITLE
Get some errors

### ISSUE THREAD

**Issue by benkitv** [wannaphongcom/pythainlp#2]
ผมได้ลง pyicu ไปแล้วครับ แล้วตามด้วยตัว pythainlp
เสร็จแล้วจะลองรันตัว test.py ดู แล้วได้ error มาตามนี้

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    from pythainlp.segment import segment
  File "/home/benkit/TH/pythainlp/pythainlp/__init__.py", line 12, in <module>
    from . import postaggers
  File "/home/benkit/TH/pythainlp/pythainlp/postaggers/__init__.py", line 2, in <module>
    from .text import tag
  File "/home/benkit/TH/pythainlp/pythainlp/postaggers/text.py", line 16, in <module>
    data1 =data()
  File "/home/benkit/TH/pythainlp/pythainlp/postaggers/text.py", line 14, in data
    model = json.load(handle)
  File "/usr/lib/python3.4/json/__init__.py", line 265, in load
    return loads(fp.read(),
  File "/usr/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 6: invalid start byte

มีคำแนะนำอะไรบ้างคับ

**Comment by wannaphongcom** [comment]
แนะนำให้เอาไฟล์ test.py มารันภายนอกไลบรารีที่เก็บ pythainlp ครับ ตอนนี้ตัว pythainlp มีปัญหาเรื่องระบบ test ครับ เวชั่นต่อไปจะแยกไฟล์ test ออกเป็นอีกระบบหนึ่ง เพื่อแก้ไขปัญหานี้ครับ
