### ISSUE TITLE
การใช้งานบางอย่างไม่แสดงผลเป็นภาษาไทย

### ISSUE THREAD

**Issue by patipol** [wannaphongcom/pythainlp#21]
การใช้งานบางอย่างไม่แสดงผลเป็นภาษาไทยครับ ไม่แน่ใจว่าผมต้องติดตั้งอะไรที่เครื่องเพิ่มเติมก่อนหรือเปล่าครับ

การแบ่งครับ ไม่แสดงผลออกมาเป็นภาษาไทยครับ
```
>>> # Thai Segment 
... from pythainlp.segment import segment
>>> a = 'ฉันรักภาษาไทยเพราะฉันเป็นคนไทย'
>>> b = segment(a)
>>> print(b)
['\xe0\xb8\x89', '\xe0\xb8\xb1', '\xe0\xb8\x99\xe0', '\xb8\xa3\xe0', '\xb8\xb1\xe0\xb8\x81', '\xe0\xb8\xa0', '\xe0\xb8\xb2\xe0', '\xb8\xa9', '\xe0\xb8\xb2']

Postaggers ก็เช่นกัน
>>> # Thai Postaggers
... from pythainlp.postaggers import tag
>>> print(tag('คุณกำลังประชุม'))
[('\xe0\xb8\x84', None), ('\xe0\xb8\xb8\xe0\xb8', None), ('\x93\xe0\xb8\x81\xe0\xb8', None)]

รวมถึงการนับจำนวนคำด้วยครับ
>>> # Find the number word of the most
... from pythainlp.rank import rank
>>> aa = rank(b)
>>> print(aa)
Counter({'\xe0\xb8\x89': 1, '\xb8\xa9': 1, '\xe0\xb8\xb2\xe0': 1, '\xe0\xb8\xa0': 1, '\xb8\xa3\xe0': 1, '\xb8\xb1\xe0\xb8\x81': 1, '\xe0\xb8\x99\xe0': 1, '\xe0\xb8\xb2': 1, '\xe0\xb8\xb1': 1})
```
ส่วนการเปลี่ยนภาษามี error ที่ `texttoeng()` ครับ
```
>>> # Fix the printer forgot to change the language
... from pythainlp.change import *
>>> a="l;ylfu8iy["
>>> a=texttothai(a)
>>> b="นามรสนอำันี"
>>> b=texttoeng(b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pythainlp/change/__init__.py", line 34, in texttoeng
    data2+=a
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 0: ordinal not in range(128)
>>> print(a)
สวัสดีครับ
>>> print(b)
นามรสนอำันี
```
การอ่านตัวเลขเป็นภาษาไทยทำได้ปกติ
```
>>> # Read a number to text in Thai language
... from pythainlp.number import numtowords
>>> print("5611116.50")
5611116.50
>>> print(numtowords(5611116.50))
ห้าล้านหกแสนหนึ่งหมื่นหนึ่งพันหนึ่งร้อยสิบหกบาทห้าสิบสตางค์
```

macOS Sierra 10.12.4
ติดตั้งตามใน README ครับ
```
$ brew install icu4c --force
$ brew link --force icu4c
$ CFLAGS=-I/usr/local/opt/icu4c/include LDFLAGS=-L/usr/local/opt/icu4c/lib pip install pythainlp
```

**Comment by wannaphongcom** [comment]
แนะนำให้ลองใส่
'''
# -*- coding: utf-8 -*-
'''
ก่อนใช้งานครับ

**Comment by patipol** [comment]
ได้แล้วครับ ขอบคุณมากครับ แต่ผมต้องใส่ prefix `u` เข้าไปด้วยครับตอนกำหนด string ภาษาไทย
ผมใช้ Python 2.7.13

```
>>> # -*- coding: utf-8 -*-
... from pythainlp.segment import segment
>>> a = u'ฉันรักภาษาไทยเพราะฉันเป็นคนไทย'
>>> b = segment(a)
>>> print(b)
[u'\u0e09\u0e31\u0e19', u'\u0e23\u0e31\u0e01', u'\u0e20\u0e32\u0e29\u0e32', u'\u0e44\u0e17\u0e22', u'\u0e40\u0e1e\u0e23\u0e32\u0e30', u'\u0e09\u0e31\u0e19', u'\u0e40\u0e1b\u0e47\u0e19', u'\u0e04\u0e19', u'\u0e44\u0e17\u0e22']
>>> print(b[0])
ฉัน
>>> print(b[1])
รัก
>>> print(b[2])
ภาษา
>>> print(b[3])
ไทย
```
