### ISSUE TITLE
please install hunspell : hunspell dictionary th_TH

### ISSUE THREAD

**Issue by IcyZKunGz** [wannaphongcom/pythainlp#29]
ผมได้ลง th_TH.dic และ th_TH.aff ลงใน ~/Library/Spelling แล้วลองรันโค๊ด
```
# -*- coding: utf-8 -*-
from pythainlp.spell import *
a=spell("สี่เหลียม")
print(a) # ['สี่เหลี่ยม', 'เสียเหลี่ยม', 'เหลี่ยม']
```

```
please install hunspell
None
```
ผมต้องแก้ไขหรือทำอะไรเพิ่มเติมเพื่อที่จะรันโค๊ดนี้มั้ยครับ
ขอบคุณครับ

**Comment by wannaphongcom** [comment]
@IcyZKunGz ไม่ทราบว่าใช้ OS อะไรครับ

**Comment by IcyZKunGz** [comment]
ใช้ macOS, Python 3.6.1 :: Anaconda custom (x86_64) ครับ

**Comment by wannaphongcom** [comment]
@IcyZKunGz  ลองสั่งติดตั้ง brew install hunspell
แล้วตั้งค่า path ด้วยคำสั่ง export C_INCLUDE_PATH=/usr/local/include/hunspell
แล้วลองรันดูครับ

**Comment by IcyZKunGz** [comment]
ทำตามที่บอกแล้วครับ ตอนนี้ขึ้น error ใหม่ครับ รันโค๊ดตัวเดิมเลยครับ
```
Traceback (most recent call last):
  File "/Users/arsapol/Desktop/test.py", line 3, in <module>
    a=spell("สี่เหลียม")
  File "/Users/arsapol/anaconda3/lib/python3.6/site-packages/pythainlp-1.4-py3.6.egg/pythainlp/spell/hunspell.py", line 18, in spell
    getoutput = subprocess.getoutput(cmd)
  File "/Users/arsapol/anaconda3/lib/python3.6/subprocess.py", line 534, in getoutput
    return getstatusoutput(cmd)[1]
  File "/Users/arsapol/anaconda3/lib/python3.6/subprocess.py", line 515, in getstatusoutput
    data = check_output(cmd, shell=True, universal_newlines=True, stderr=STDOUT)
  File "/Users/arsapol/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/Users/arsapol/anaconda3/lib/python3.6/subprocess.py", line 405, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/Users/arsapol/anaconda3/lib/python3.6/subprocess.py", line 823, in communicate
    stdout = self.stdout.read()
  File "/Users/arsapol/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 17: invalid continuation byte
[Finished in 5.8s]
```

**Comment by wannaphongcom** [comment]
ลองเอาไฟล์ th_TH.dic และ th_TH.aff ลงใน /Library/Spelling/ ใหม่ครับ
แล้วใช้ hunspell -D เช็คว่ามีไฟล์ไหมครับ

**Comment by IcyZKunGz** [comment]
มันขึ้นมาอย่างนี้ครับ
```
AVAILABLE DICTIONARIES (path is not mandatory for -d option):
/Users/arsapol/Library/Spelling/en_US
/Users/arsapol/Library/Spelling/th_TH
LOADED DICTIONARY:
/Users/arsapol/Library/Spelling/en_US.aff
/Users/arsapol/Library/Spelling/en_US.dic
Hunspell 1.6.1
```

**Comment by wannaphongcom** [comment]
@IcyZKunGz ใช่ครับ
