### ISSUE TITLE
Library not loaded: libicui18n.54.dylib

### ISSUE THREAD

**Issue by topskychen** [wannaphongcom/pythainlp#50]
`>>> from pythainlp.tokenize import word_tokenize
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/qianchen/.pyenv/versions/anaconda2-4.4.0/lib/python2.7/site-packages/pythainlp/__init__.py", line 15, in <module>
    from pythainlp.date import now
  File "/Users/qianchen/.pyenv/versions/anaconda2-4.4.0/lib/python2.7/site-packages/pythainlp/date/__init__.py", line 3, in <module>
    import icu
  File "/Users/qianchen/.pyenv/versions/anaconda2-4.4.0/lib/python2.7/site-packages/icu/__init__.py", line 42, in <module>
    from docs import *
  File "/Users/qianchen/.pyenv/versions/anaconda2-4.4.0/lib/python2.7/site-packages/icu/docs.py", line 23, in <module>
    from _icu import *
ImportError: dlopen(/Users/qianchen/.pyenv/versions/anaconda2-4.4.0/lib/python2.7/site-packages/_icu.so, 2): Library not loaded: libicui18n.54.dylib
  Referenced from: /Users/qianchen/.pyenv/versions/anaconda2-4.4.0/lib/python2.7/site-packages/_icu.so
  Reason: image not found`

When I was trying to `word_tokenize`, I met this error.
This is my python version: Python 2.7.13 |Anaconda 4.4.0 (x86_64)| (default, Dec 20 2016, 23:05:08) 
My mac os version is 10.11.6

Thanks for your attention.

**Comment by wannaphongcom** [comment]
Have you tried this yet? https://medium.com/data-science-cafe/install-polyglot-on-mac-3c90445abc1f

**Comment by topskychen** [comment]
just tried. not working for me. it looks like it cannot find the `libicui18n.54.dylib`?

**Comment by wannaphongcom** [comment]
https://github.com/aboSamoor/polyglot/issues/80#issuecomment-266301717

**Comment by topskychen** [comment]
it works. 
`conda install -c ccordoba12 icu=54.1`
`ipython`
`!easy_install pyicu`
